### ISSUE TITLE
Source file not found (Execute.cs)

### ISSUE THREAD

**Issue by KyeNormanGill** [Zaczero/SharpLoader#1]
I tried copying Yami hack from the sharploader release on mpgh. I generated the settings file and also copied the references/sources. Yet when i run it i get.

Source file not found (Execute.cs)

**Comment by Zaczero** [comment]
You should check "Sources" section.
There is a problem with "Execute.cs" path so it can't be found.
There aren't many changes so I would recommend you using SharpLoader v1.2 that is uploaded within Yami on mpgh.

SharpLoader v1.3 supports "Directory" configuration that is not implemented in the old Yami and here may be the problem.
https://github.com/Zaczero/SharpLoader#directory
https://github.com/Zaczero/SharpLoader#sources

Alternatively you can send SharpLoader.ini settings here and I'll take a look on them.

**Comment by KyeNormanGill** [comment]
```[SharpLoader]
References=System.dll;System.Windows.Forms.dll;System.Web.Extensions.dll
Directory=Yami
Sources=Execute.cs;Global.cs;Memory.cs;Offsets.cs;Program.cs;Sig.cs;SigScan.cs;WinApi.cs;Objects\LocalPlayer.cs;Objects\Player.cs;Structs\GlowColor.cs;Structs\RenderColor.cs;Structs\StructParser.cs
Output=Yami
Arguments=/platform:anycpu32bitpreferred
AutoRun=false
```

That's what i have for the settings file

Sorry for the late response

**Comment by KyeNormanGill** [comment]
Removing the sources fixed the missing execute.cs but now i have.

```
c:\Users\kyeno\AppData\Local\Temp\fxt3vbts.9.cs(1,4391) : error CS0246: The type or namespace name 'GlowColor' could not be found (are you missing a using directive or an assembly reference?)
c:\Users\kyeno\AppData\Local\Temp\fxt3vbts.9.cs(1,11661) : error CS0246: The type or namespace name 'RenderColor' could not be found (are you missing a using directive or an assembly reference?)
```

**Comment by KyeNormanGill** [comment]
Nevermind i fixed it. :|

**Comment by Zaczero** [comment]
Nice to hear that =)
Also to clarify  everything:
```
Directory=Yami
Sources=Execute.cs;(...)
```
means that Execute.cs file is inside Yami folder and that Yami folder is in the same directory as SharpLoader
