### ISSUE TITLE
metadata file "System.D" could not be found (SharpLoader 2.0)

### ISSUE THREAD

**Issue by SupportExTraGoZ** [Zaczero/SharpLoader#3]
metadata file "System.D" could not be found (SharpLoader 2.0)

**Comment by Zaczero** [comment]
Can you provide some more info?
When did you get that error?
You can attach screenshot which could be very useful.

**Comment by SupportExTraGoZ** [comment]
When I was compiling it, yeah sure let me attach screenshot.

**Comment by SupportExTraGoZ** [comment]
http://i.imgur.com/ruej7cW.png
[SharpLoader]
References=System.Numerics.Vectors.dll;SlimDX.dll;log4net.dll;MetroFramework.Design.dll;Metroframework.dll;Metroframework.Fonts.dll;Newtonsoft.Json.dll;BlueRain.dll;CheatNameFirst.dll;CheatNameSecond.dll;System.dll;System.Core.dll;System.Data.dll;System.Deployment.dll;System.Drawing.dll;System.Management.dll;System.Windows.Forms.dll;System.Xml.dll;System.Xml.Linq.dll
Directory=Rel
Sources=
Output=Release
Arguments=/platform:anycpu32bitpreferred
AutoRun=false

**Comment by Zaczero** [comment]
I think I know the reason.
.ini read buffer is set to 256 characters.
I'll increase it and make an update in few mins.

**Comment by SupportExTraGoZ** [comment]
Okay I'll wait

**Comment by Zaczero** [comment]
https://github.com/Zaczero/SharpLoader/releases
