### ISSUE TITLE
Add support for preprocessor directives

### ISSUE THREAD

**Issue by SupportExTraGoZ** [Zaczero/SharpLoader#5]
Hey man,

I already feel like trouble-ing you too much damn xD
But I get errors now when I compile -> 
`F:\MyUser\Program Files\TrashV2\iq3a35d3.1.cs(1,5985) : error CS1040: Preprocessor directives must appear as the first non-whitespace character on a line
F:\MyUser\Program Files\TrashV2\iq3a35d3.1.cs(1,7304) : error CS1513: } expected`
And they continue down the same issues, like 5/6 more of those, I've did research in internet, but it's really not compiling error in the code, since I'm able to compile it on VS 2017

Cheers!

**Comment by Zaczero** [comment]
Try to remove all custom vs code from it like:
#region
#endregion
#if
#else
#endif
#define
etc.
SharpLoader doesn't support that.

**Comment by SupportExTraGoZ** [comment]
I'll do that, but is it possible to make it so it supports that? xD

**Comment by Zaczero** [comment]
Everything is possible ;)

**Comment by SupportExTraGoZ** [comment]
Yeah, I've done that on my project, but my project also uses other DLL's not made/developed by me, they have #region etc etc there, and that's yet causing again the error, will wait for the fix.

**Comment by Zaczero** [comment]
If you got Skype add me: MrZaczer0 
I think that this .dll error is caused by another bug :D
It doesn't matter for the .dll if there is #region in it or not.

**Comment by SupportExTraGoZ** [comment]
Eh, I don't use skype much atm :S -> Well I don't know what that error could be from :S

**Comment by Zaczero** [comment]
Any other contact method?
Can you paste this error here?

**Comment by SupportExTraGoZ** [comment]
Eh will try to figure out, probably make skype or yeah :D -> I'll paste it in a moment

**Comment by SupportExTraGoZ** [comment]
`error CS1040: Preprocessor directives must appear as the first non-whitespace character on a line
F:\MyUser\Program Files\TrashV2\i3zlcu5x.8.cs(1,5327) : error CS1513: } expected
F:\MyUser\Program Files\TrashV2\i3zlcu5x.8.cs(1,5327) : error CS1038: #endregion directive expected
F:\MyUser\Program Files\TrashV2\i3zlcu5x.5.cs(1,28) : warning CS1696: Single-line comment or end-of-line expected
F:\MyUser\Program Files\TrashV2\i3zlcu5x.2.cs(1,255) : error CS1040: Preprocessor directives must appear as the first non-whitespace character on a line
F:\MyUser\Program Files\TrashV2\i3zlcu5x.2.cs(1,992) : error CS1513: } expected
F:\MyUser\Program Files\TrashV2\i3zlcu5x.2.cs(1,992) : error CS1038: #endregion directive expected`

**Comment by SupportExTraGoZ** [comment]
I'll continue tomorrow, if you can think of a way to fix this, I'll be so glad to hear and assist.

**Comment by Zaczero** [comment]
Looks like that preprocessor support will do the job.

**Comment by Zaczero** [comment]
https://github.com/Zaczero/SharpLoader/releases
