### ISSUE TITLE
WindowsBase.dll MetaData Cannot be found

### ISSUE THREAD

**Issue by jellythedoge** [Zaczero/SharpLoader#6]
-=: SharpLoader v2.2
-=: Created by Zaczero
-=: Seed : 1612974352

-=: Reading...
-=: Randomizing...
-=: Compiling...
-=: Compilation error
error CS0006: Metadata file 'WindowsBase.dll' could not be found

**Comment by jellythedoge** [comment]
Im retarded i spelled them wrong but WindowsBase still doesnt exist :/

**Comment by Zaczero** [comment]
Add me on Skype: MrZaczer0

**Comment by Zaczero** [comment]
use WPF\WindowsBase.dll
instead of WindowsBase.dll
