### ISSUE TITLE
Error CS1022: Type or namespace definition, or end-of-file expected

### ISSUE THREAD

**Issue by TetteDev** [Zaczero/SharpLoader#9]
Hello!

No matter what project I try to use with your program, the compilation process returns
`error CS1022: Type or namespace definition, or end-of-file expected`

![img](https://user-images.githubusercontent.com/6103339/47304773-d4f9a800-d627-11e8-95c2-f85a7a0b6d42.png)

The project compiles and runs perfectly fine when compiling via visual studio.

**Comment by Zaczero** [comment]
So what was causing the problem ? @Sadulisten

**Comment by TetteDev** [comment]
No Idea. I thought you had perhaps abandoned this project.
I went and recreated it to some degree to myself as I thought it was quite smart.

**Comment by Zaczero** [comment]
It's a bit abandoned but I don't ignore the issues.
All projects which are not archived are still supported by me.

However the code is a bit old and really ugly written.
If I ever make any improvements it would be a v2 recode.

It's hard to spot bugs when the code is messy af ;)
I am happy that you solved the problem though!
